[build-system]
requires = ["pbr>=5.7.0", "setuptools>=36.6.0"]
build-backend = "pbr.build"

[tool.black]
line-length = 100
target-version = ['py35']

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 100
